import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Components/Header'
import Footer from './Components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={`${inter.className} h-screen bg-light-Secondary dark:dark-Seconday`}>
      <Header />
      <section id='body' className=''>
        <div className='container mx-auto flex'>
      {children}
      </div>
      </section>
        <Footer />
          </body>
      
    </html>
  )
}
